-- LIMIT CLAUSE => USED TO SET AN UPPER LIMIT ON NUMBER OF TUPLES (ROWS) TO BE RETURNED

USE IP_PROJECT;
SELECT * FROM ACCNT_BAL ORDER BY ACC_BALANCE DESC LIMIT 5; -- Data Of Top 5 Users With Highest Account Balance