-- ORDER BY => USED TO SORT DATA 

USE IP_PROJECT;
SELECT ACC_NO, NAME, DATE(DATE_OF_BIRTH) FROM ACCOUNTS ORDER BY DATE_OF_BIRTH;

USE IP_PROJECT;
SELECT ACC_NO, NAME, DATE(DATE_OF_BIRTH) FROM ACCOUNTS ORDER BY NAME DESC;