-- AGGREGATE FUNCTIONS => THESE ARE FUNCTIONS THAT ARE USED TO PERFORM CALCULATIONS ON DATA FIELDS
-- THESE FUNCTIONS ALWAYS RETURN A SINGLE VALUE.

-- 1.) COUNT FUNCTION => USED TO COUNT ALL THE NOT NULL VALUES PRESENT IN THE SELECTED FIELDS
USE IP_PROJECT;
SELECT COUNT(*) As Male_Customers_Count FROM ACCOUNTS WHERE GENDER LIKE "M%";

-- 2.) MAX FUNCTION => USED TO FIND THE MAXIMUM VALUE FROM A GIVEN DATA FIELD
USE IP_PROJECT;
SELECT MAX(ACC_BALANCE) AS "MAX ACCOUNT BALANCE" FROM ACCNT_BAL;

-- 3.) MIN FUNCTION => USED TO FIND THE MINIMUM VALUE FROM A GIVEN DATA FIELD
USE IP_PROJECT;
SELECT MIN(ACC_BALANCE) AS "MIN ACCOUNT BALANCE" FROM ACCNT_BAL;

-- 4.) SUM FUNCTION => USED TO FIND THE SUM OF ALL MATHEMATICAL VALUES PRESENT IN A DATA FIELD
USE IP_PROJECT;
SELECT SUM(ACC_BALANCE) AS "TOTAL MONEY IN BANK" FROM ACCNT_BAL;

-- 5.) AVG FUNCTION => USED TO FIND THE AVERAGE OF ALL THE VALUES PRESENT IN A DATA FIELD
USE IP_PROJECT;
SELECT AVG(ACC_BALANCE) AS "AVERAGE ACCOUNT BALANCE" FROM ACCNT_BAL;