-- HAVING CLAUSE => USED TO APPLY CONDITION ON GROUPS AFTER USING GROUP BY CLAUSE
-- CAN ONLY BE SUED AFTER GROUP BY CLAUSE

-- DISPLAY ALL THE RESIDENTIAL ADDRESSES HAVING MORE THAT 1 PERSONS LIVING ON THEM.
USE IP_PROJECT;
SELECT RESIDENTIAL_ADDRESS AS ADDRESS, COUNT(*) AS "CUSTOMER COUNT" FROM ACCOUNTS
GROUP BY RESIDENTIAL_ADDRESS 
HAVING COUNT(*) > 1;

-- GENERAL ORDER : 
-- SELECT *** FROM *** WHERE *** GROUP BY *** HAVING *** ORDER BY *** LIMIT