-- UPDATE TABLE : USED TO REPLACE EXISTING DATA IN DATABASE WUTH NEW VALUES

USE IP_PROJECT;
SELECT * FROM ACCOUNTS;

USE IP_PROJECT;
UPDATE ACCOUNTS SET NAME = "Anisha Bhatt", GENDER = "Female" WHERE NAME = "Anish Bhatt";

USE IP_PROJECT;
UPDATE ACCOUNTS SET NAME = "Anshika", GENDER = "Female" WHERE NAME = "Anish Bhatt";