-- ALTER => USED TO CHANGE THE SCHEMA OF OUR TABLES

USE AKSHAT;
SELECT * FROM APPLICATIONS;

USE AKSHAT;
SELECT * FROM STREAM;

USE AKSHAT;
SELECT * FROM STUDENT;

-- 1.) CHANGE TABLE NAME :
USE AKSHAT;
ALTER TABLE CLUB RENAME TO APPLICATIONS;

-- 2.) ADDING NEW FIELDS :
USE AKSHAT;
ALTER TABLE STREAM ADD COLUMN Class INT DEFAULT 12;

-- 3.) DELETING EXISTING FIELDS : 
USE AKSHAT;
ALTER TABLE STREAM DROP COLUMN CLASS;

-- 4.) RENAME EXISTING FIELS :
USE AKSHAT;
ALTER TABLE APPLICATIONS CHANGE COLUMN Pay Salary INT;  --    Pay => OLD NAME, Salary => NEW NAME

-- 5.) MODIFY COLUMN ( DATATYPE OR CONSTRAINTS ) :
USE AKSHAT;
ALTER TABLE STSREAM MODIFY STCODE VARCHAR(5) UNIQUE;